defmodule Aoc.Day07Test do
  use ExUnit.Case, async: true

  @moduletag :day07

  import Aoc.TestHelper
  alias Aoc.Runner

  @example_input """
  .......S.......
  ...............
  .......^.......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............  
  """

  @tag :day07_part1
  test "part1" do
    {_, actual} = Runner.run(7, 1, stream_in(@example_input))

    assert actual == 21
  end

  @tag :day07_part2
  test "part2 " do
    {_, actual} = Runner.run(7, 2, stream_in(@example_input))

    assert actual == 40
  end
end
